---
title: "About"
output: html_document
---

This site is built entirely on R Markdown site generator in its simplest form with minimum coding, packages and themes. To learn more about R Markdown, go to: <https://rmarkdown.rstudio.com/index.html> or read the book, R Markdown: The Definitive Guide online <https://bookdown.org/yihui/rmarkdown/rmarkdown-site.html>.

I will share random stuff on this blog that I think would be useful information for you. I have not opened the site to comments yet. You can contact me at shtan06@gmail.com.

 *"...break (the projects) down to their simplest form and then just make marginal improvements along the way to improve my odds of achieving them."*
 - an inspiring advise from Stephen Duneier who gave a talk on TEDx on how to achieve your goals.
 
 <br>
 <br>
 <br>
 
 ### Update (Sep 2020)
 
 <br>
 
 I am shutting down my inv-ops website, have removed all the contents and gradually posting some of them to this site. Apologies if you find this site incomplete or even disorganised at this time. Until my new website is up, you can find my profile, tutorial materials, training and programming write-ups all packed into this tiny space.
 