---
title: "Get Flask Up and Running with Anaconda Navigator"
output: html_document
---

Executing commands from your Terminal or Command Prompt is almost unavoidable in Python. You will find that many course instructors use them to perform even simple tasks like opening a file. Beginners following step-by-step may find it difficult to make sense of what is going on in the command line environment.

If you are eager to get your first Flask project started, but find the initial setup confusing, here are the steps to follow to get you started painlessly.

* __One-time setup__
  + Create a new environment for your project
  + Install flask in the new environment
  + Install Spyder in the new environment (optional)
  
* __Run your application__
  + Run your .py file

* __You are done with flask for the day__
  + Stop the server
  
The overall setup is like any other flask installation, but with Anaconda Navigator, the process is simplified because you don't have to worry about the command line.

I assume you have installed Anaconda Navigator, if not, here is the [link](https://www.anaconda.com/products/individual). Your installation includes the _flask_ package, but only in the base environment.

_Note: I am using MacOS 10.15. My Anaconda Navigator version is 1.9.12 and Python version is 3.7. The steps below applies to both Mac OS and Windows._  
\

#### One-time Setup

##### 1. Create a new environment for your project
* Open the Anaconda Navigator app
* On the left pane, click _Environments_
* At the bottom of the page, click _Create_
* Enter a new environment name eg. virenv
* Make sure the location and Python version are displayed. If not, re-start the app and do not launch any other applications within the app yet
* Take note of the default _Location_ because this is where you will be saving your files later.
* Click _Create_ and wait for the setup to complete.

##### 2. Install flask in the new environment
* The new environment will automatically pre-load about a dozen packages but does not include flask
* On the right panel of the _Environments_ page, look for the drop down list at the top where the defult value is "installed". Select "All".
* Search "flask"
* Select _flask_ by clicking on the checkbox. There are other flask extensions but you can ignore those for now.
* Click apply
* Anaconda will install flask and its dependecies.

##### 3. Install Spyder in the new environment
* On the Home page of the Navigator, select your new environment name in the _Applications on_ drop down list.
* Click on the Install button in the Spyder box  
_(You can install your favourite IDE if you like. My default IDE is IDLE but it seems to have an issue with Ctrl-C to stop the server.)_

##### 4. Create a .py file and folders
* Launch Spyder
* Write a basic flask code like the one below and save it in the _virenv_ (or whatever name you had chosen to call it) folder. In this example, let's call it main.py.

      from flask import Flask
      
      app = Flask(__name__)
      
      @app.route("/")  
      def home():  
      return "Hello, World!"
      
      if __name__ == "__main__":  
      app.run(debug=True)

* Using your Finder or Windows Explorer, create two blank folders inside the _virenv_ folder: _static_ and _templates_ (you don't have to at this point but you are going to end up creating them anyway)

That's all for the one-time setup.   
\

#### Run your application (main.py)
* Launch Spyder from the Home page of Anaconda Navigator. Make sure that you select the correct environment from the *Applications On* drop-down list (for Windows user, you can launch Spyder directly but choose the one that shows your environment name).
* Open your main.py file located in ../opt/anaconda3/envs/virenv (if you are using Mac)
* Click the Run button.
* Your can now start working on your application. No *export* or *flask run* command line required.


Test if it works by typing "localhost:5000" in your browser. If you make changes to the file, just save it and run the file again from Spyder. Make sure to check the console that the reload is successful.  
\

#### You are done with flask for the day
* Move your cursor to the Spyder console and type Ctrl-C to quit. If you are using Windows, right click on the comsole and select *Quit*.
\
\

So, that's it. I hope this was easy enough for you to follow and you managed to setup your environment without any problems.








