---
title: "Why R?"
date: "2 May 2020"
output: html_document
---
Edit this.

If you are already reading this, I assume you have decided to learn R, or at least making it as one of your top choices.

R basically works like a statistics application but gives you the flexibility to customise how you want to build your data, output, model and so on. It does more than just statistical analysis. You can analyse data and write many mathematical formulas that are used in industries from finance to engineering and education. In short, R is commonly used where there is __data__ for you to analyse.

Data, according to definition, is information collected together for reference or analysis. Whether the data is a small random sample, big data or data derived from a predictive model, it is worth noting that these data can be sourced because it exists, since an event (to collect) has happened. So, this is the kind of data you deal with in R. 

It is rare for R to handle collections of actual data (transaction processing). Think of R as more of a analytical or business intelligence tool that has many built-in statistical functions and its own programming language. There are many R packages that have great enhancing features but it is essentially a program that is designed with data analysts and statisticians in mind. If you got into R thinking you can develop high traffic e-commerce websites, fintech systems, gaming apps or AI drones, well, technically it may be possible but I can't say for sure if the codes are not going to get messy.

If you are very sure that your main objective is to work with data, then R is one of the best out there. It is not only easy to learn, but fun as well. It also offers some amazing packages if you are not messing with your data. Check out this [link](https://simplystatistics.org/2019/03/13/10-things-r-can-do-that-might-surprise-you/).