---
title: "What Motivates You to Learn Programming?"
date: "1 May 2020"
output: html_document
---

Let's have a bit of fun categorising the reasons for people getting started in programming. Which one do you belong to? No surveys here, just keep the answers to yourself. 

* I love everything about gadgets and technology. People around me share the same interest. I'm learning programming like its my natural second language.

* Everyone's into it. I should give it a go. Maybe I will like it.

* My friend works at Google. Say no more.

* My MBTI personality type suggests this field is best suited for me.  

* I use spreadsheet a lot at work and have access to the sales database. I want to impress my boss and shine above my colleagues with state-of-the-art presentation and analysis.

* My career is stale. For the past eight years, there was nothing to update in my resume and LinkedIn.

* I just built my own website without any code. I want to take my IT skill to a new level and who knows, I could freelance and earn extra income.

* I want to start my own business and in today's world of e-commerce, some basic programming knowledge could contribute to decision-making.

* That's a good question, John.

* I want to change the world (sure, good luck!).
