---
title: "Session Two: The RStudio Environment"
author: "Estimated Duration: 1 hour"
output:
  html_document: 
    code_folding: show
    highlight: tango
    number_sections: no
    theme: sandstone
    toc: yes
    toc_depth: 5
    toc_float:
      collapsed: no
      smooth_scroll: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<br>

# {.tabset}

## 1. The RStudio Environment

### __Part 1: The RStudio Environment__

<br>

#### R Script File

R code can be run from the console or R Script file. Codes written in an R Script file can be saved in any directory and has a .R extension.  

* Exercise
  + Create a new R Script file and enter/run a code to populate the environment. Save the file.

<br>

#### Session

Launching RStudio opens a session. You can open multiple sessions.  

<br>

##### • Environment

An environment stores user-defined objects. The workspace is your current environment and is usually the global environment. Use environment() to display the name of the environment.

<br>

##### • Working Directory

The working directory is the file path of the current environment and is the default location where files are read from and saved into.  

If the environment contains objects, saving your workplace when exiting RStudio creates a .RData file in the current working directory. This file has no name and is usually a hidden file in your O/S directory, but you can view it from the Files pane in RStudio.  

Use getwd() to show the path of the working directory and setwd() to set a new working directory. Alternatively, go to the Session menu in RStudio to change the directory. The current path is displayed just below the Console tab.  

<br>

##### • Launching RStudio

Launching RStudio directly from the application restores the default working directory (specified in the Preferences settings) and the .RData environment in that directory.

Launching RStudio from an R file restores the working directory and environment of the .RData file where both files are located, and not the default directory. If the same R file is moved to a different folder, opening it directly will restore the working directory and .RData (if any) of that folder.

<br>

##### •	Tip

Save all R files belonging to the same project in a specific folder with its own RData file. Since you can open any R files not related to the project in the same session, it can get messy when unrelated objects are stored in the current environment. Always check your workspace to ensure it is pointing to the right working directory and that the environment values are relevant. Open different sessions for different projects.

<br>

##### •	Exercise

  +	Open a new RStudio session and create a new R script file and save.
  + Create a new vector, for example: x <- “green”.
  + Run the code to store the value in the global environment.
  +	Take note of where the R and RData files are located.
  +	Copy the R file to a new folder and rename it. Run the file directly from the directory.
  +	Observe the working directory path and global environment pane.
  +	Run the code, exit and save workplace image.
  +	Note where the new .RData has been created.
  +	Set the working directory back to the default path. Create another vector from the second R file and run the code. In which environment was the vector value stored?

<br>

#### Preferences

Overview of the General, Appearance and Pane Layout settings.

Further reading
https://support.rstudio.com/hc/en-us/articles/200549016-Customizing-RStudio

<br>

#### Project

Creating a project designates a working directory with a .RProj file. When you open a project, the working directory will automatically be set to the directory that the RProj file is located in.

##### •	Exercise

  + Create a new project from RStudio and briefly describe the differences between New Directory, Existing Directory and Version Control.
  +	Observe the files that have been created in the directory.

<br>
<br>

## 2. Packages

### __Part 2: Packages__

<br>

#### About Packages

•	An R package is a collection of functions, data and documentation created by the R community and can be shared with others. Packages are designed for many different uses – financial, data manipulation, statistics, graphs and many more.  

•	Packages are stored in repositories where you can access and install packages from. Repositories such as CRAN and github are available to the public, or you can have your own local repository to share user-defined packages within your own organisation.  
 
__Package Information__  

Click the package name in the Packages tab or use ??packagename or Vignettes. Type browseVignettes() for list of vignettes of installed packages (not all packages have vignettes) or browseVignettes(“package name”).  

Use RSiteSearch(“package name”) if package has not been installed in your computer.  

Cheatsheets: these provide essential codes and are available on the internet.  

<br>

#### Installing Packages

RStudio’s packages tab shows all installed packages, grouped by system library and user library. Core or base packages are installed with R and are typically located in the system library. Other packages that are installed separately can be found in the user library. Each library is located in a different directory in your computer (for Mac, if there is only a single library path, then it will only display system library since all packages are installed in the same directory). Boxes that are checked indicates the package is already loaded.  

To find the path of the package library, type .libPaths() or click install from the Packages tab and the default path is shown in the drop-down list.  

Packages can be installed in three ways:

  *	Using RStudio’s Install function
  *	Using install.packages(“packagename”) command in R
  *	Using R CMD INSTALL command in the shell (aka Terminal)
  
After installation, load the package by either typing library(packagename) in the console or clicking the check box next to the package in the Packages tab.  

Note:  
  *	If you have the package files already downloaded into your computer, select “Package Archive File” from the Install function.
  *	To install packages from Github, you need to install devtools first. Then type install_github(“packagename”, “user name”).
  *	To display a list of all the packages that are available in the CRAN repository, use View(available.packages())
  *	To uninstall packages, use remove.packages().

<br>

#### Useful Packages

We have seen from Session 1 (Introduction to R) the main purpose of using R, that is to capture, clean, analyse and present data. There are thousands of packages to choose from and here are some popular and useful ones.  

__Data Loading__  
DBI, odbc, RMySQL, RPostgresSQL, RSQLite, XLConnect, xlsx  

__Manipulate Data__  
dplyr, tidyr, stringr, lubridate, magrittr  

__Visualise Data__  
ggplot2, plotly, ggvis, rgl, essquise, htmlwidgets, leaflet, dygraphs, DT, diagrammeR, network3D, threeJS, goggleVis, kable/kableExtra, DataExplorer  

__Spatial Data__  
sp, maptools, maps, ggmap  

__Publishing__  
RMarkdown, Flexdashboard, shiny, Radiant  

__Time Series and Financial Data__ 
zoo, xts, quantmod  

__High Performance__  
data.table, parallel (now a core package)  

__Write Packages__ 
devtools, testthat, roxygen2  

… and many other packages and plugins for statistical analysis, statistical models, simulations, machine learning, deep learning, etc.  

<br>

__Resources__

1.	R for Mac OS X FAQ https://cran.r-project.org/bin/macosx/RMacOSX-FAQ.html#Where-are-the-packages-I_0027ve-installed_003f

<br>
<br>
