---
title: "Session Three (a): Coding - Arithmetic Operators and Functions"
author: "Estimated Duration: 20 minutes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<br>

## Arithmetic Operators and Functions

<br>

#### Operators

Operator | Description | Example | Results
-------- | ----------- | ------- | -------
+        | Add         | `5+3`     | `r 5+3`
-        | Subtract    | `8-6`     | `r 8-6`
*        | Multiply    | `4*2`     | `r 4*2`
/        | Divide      | `9/3`     | `r 9/3`
^ or **  | Exponent    | `2^3`     | `r 2^3`
%%       | Remainder after division (mod) | `10%%3` | `r 10%%3`
%/%      | Integer division | `10%/%3`, `6.8%/%1` | `r 10%/%3` , `r 6.8%/%1`

<br>

#### Arithmetic

Function | Description | Example | Results
-------- | ----------- | ------- | -------
sqrt     | Square root | `sqrt(36)`| `r sqrt(36)`
abs      | Absolute    | `abs(-6)` | `r abs(-6)`
factorial(x) | Factorial | `factorial(4)` | `r factorial(4)`
round(x,d.p.)| Round     | `round(pi,6)`  | `r round(pi,6)`

<br>

#### Constants

Function | Description | Example | Results
-------- | ----------- | ------- | -------
pi       | pi          | `pi+0`  | `r pi+0`
exp      | e           | `exp(1)`| `r exp(1)`

<br>

#### Logarithm

Function | Description | Example | Results
-------- | ----------- | ------- | -------
log(x,base) | log      | `log(9,3)`| `r log(9,3)`
log10() | log base 10 | `log10(1000)` | `r log10(100)`
log()   |natural log base e | `log(30)` |`r log(30)`

<br>

#### Trigonometry

Function | Description | Example | Results
-------- | ----------- | ------- | -------
sin(x)   | Sin         | `sin(0.68)` | `r sin(0.68)`
cos(x)   | Cos         | `cos(0.68)` | `r cos(0.68)`
tan(x)   | Tan         | `tan(0.68)` | `r tan(0.68)`
Note: x is in radians  

<br>

#### Statistics

Function | Description | Example | Results
-------- | ----------- | ------- | -------
max(x)   | Maximum     | `max(c(5,9,-3,12,7,4))` | `r max(c(5,9,-3,12,7,4))`
min(x)   | Minimum     | `min(c(5,9,-3,12,7,4))` | `r min(c(5,9,-3,12,7,4))`
sum(x)   | Sum         | `sum(c(7,6,8,5,9))`     | `r sum(c(7,6,8,5,9))`
mean(x)  | Mean        | `mean(c(7,6,8,5,9))`    | `r mean(c(7,6,8,5,9))`
median(x)| Median      | `median(c(7,6,8,5,9))`  | `r median(c(7,6,8,5,9))`
var(x)   | Variance    | `var(c(7,6,8,5,9))`     | `r var(c(7,6,8,5,9))`
sd(x)    | Standard deviation | `sd(c(7,6,8,5,9))` | `r sd(c(7,6,8,5,9))`
sample(x, size, replace) | Random sample | `sample(10,5,TRUE)` | `r sample(10,5,TRUE)` 
choose(n,r) | Combination| `choose(5,3)`   | `r choose(5,3)`
runif(n, min, max)       | Uniform random number | `runif(2,1,5)` | `r runif(2,1,5)`
rnorm(n, mean, sd)       | Normal random number  | `rnorm(2)`     | `r rnorm(2)`

<br>

#### Calculus

Function | Description | Example | Results
-------- | ----------- | ------- | -------
D(expression(f(x),'x') | Differentiation | `D(expression(2*x),'x')` | `r D(expression(2*x),'x')`
